export const HttpStatusCode = Object.freeze({
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  AMBIGUOUS: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  I_AM_A_TEAPOT: 418,
  MISDIRECTED: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
});

export const HttpStatusMessage = Object.freeze({
  CONTINUE: "CONTINUE",
  OK: "OK",
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  NO_CONTENT: "NO_CONTENT",
  RESET_CONTENT: "RESET_CONTENT",
  PARTIAL_CONTENT: "PARTIAL_CONTENT",
  AMBIGUOUS: "AMBIGUOUS",
  MOVED_PERMANENTLY: "MOVED_PERMANENTLY",
  FOUND: "FOUND",
  NOT_MODIFIED: "NOT_MODIFIED",
  TEMPORARY_REDIRECT: "TEMPORARY_REDIRECT",
  PERMANENT_REDIRECT: "PERMANENT_REDIRECT",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE: "NOT_ACCEPTABLE",
  PROXY_AUTHENTICATION_REQUIRED: "PROXY_AUTHENTICATION_REQUIRED",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  CONFLICT: "CONFLICT",
  LOCKED: "LOCKED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});

export const SocketStatusMessage = Object.freeze({
  CONTINUE: "CONTINUE",
  OK: "OK",
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  NO_CONTENT: "NO_CONTENT",
  FAIL: "FAILED",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
});

export const ExceptionMessage = Object.freeze({
  DEFAULT_MESSAGE: "An unknown error occurred, please try again later.",
  EMAIL_ALREADY_EXIST: "This email is already registered.",
  VERIFICATION_FAILED: "Email verification failed. Please try again.",
  EMAIL_NOT_EXISTS:
    "Seems like the Email is not registered with us. Please try to login using another Email",
  LOGIN_FAILED: "Login failed. Please check your credentials.",
  INVALID_PASSWORD: "Invalid Password",
  SOMETHING_WENT_WRONG: "Something went wrong. Please try again later.",
  USER_NOT_EXISTS: "User does not exist.",
  USER_ALREADY_EXIST: "User already exists.",
  AUTH_INVALID_TOKEN: "Invalid authentication token. Please log in again.",
  SESSION_EXPIRED: "Your session has been expired. Please log in again.",
  AUTH_INVALID_STRATEGY: "Invalid authentication strategy.",
  OTP_EXPIRED: "The OTP has expired. Please request a new one.",
  MISSING_PERMISSION_TOKEN: "Missing permission token. Please log in again.",
  INTERNAL_SERVER_ERROR: "Internal server error. Please try again later.",
  INVALID_ROUTE: "Endpoint is not valid.",
  TOKENIZATION_ERROR: "Invalid Token",
  NO_ACK: "Acknowledgement function not provided.",
  USERNAME_ALREADY_EXIST: "Username already exist.",
  MOBILE_NO_ALREADY_EXIST: "Mobile number already exist.",
  OTP_INVALID: "Invalid OTP",
  PET_NOT_EXISTS: "Pet does not exist.",
  NOT_AUTHORISED: "You are not authorized to perform this action.",
  POST_NOT_EXISTS: "Post does not exist.",
  FAQ_NOT_EXISTS: "FAQ does not exist.",
  CMS_NOT_EXISTS: "CMS does not exist.",
  CMS_ALREADY_EXISTS: "CMS already exist.",
  INBOX_NOT_EXISTS: "Inbox does not exist.",
  ALREADY_BLOCKED: "You already blocked this user.",
  ALREADY_ACTIVE: "You have not blocked this user.", // admin message
  OLD_PASSWORD_NOT_TO_NEW_PASSWORD:
    "The new password should not match the old password.",
  NOT_BLOCKED: "You have not blocked this user.", // user message
  ACCOUNT_DEACTIVATED:
    "You have been deactivated from admin, please contact admin to sign in to the application",
  INVALID_FILE_EXTENSION: "Invalid file extension.",
  OLD_PASSWORD_IS_INCORRECT: "Old password is incorrect.",
  SHOP_NOT_EXIST: "Shop does not exist.",
  HOSPITAL_NOT_EXIST: "Hospital does not exist.",
  NOT_ONLINE: "Receiver is not online.",
  NOTIFICATION_NOT_EXISTS: "Notification does not exist.",
  ALREADY_RAISED_TRANSFER_OWNERSHIP:
    "You have already raised transfer ownership for this pet.",
  NO_TRANSFER_OWNERSHIP: "Transfer ownership detail does not exist.",
  CANCEL_UNDER_24_HRS: "You cannot cancel transfer ownership after 24 hours.",
  ROOM_ID_NOT_PROVIDED: "Room ID is not provided.",
  ALREADY_PARTNER:
    "It looks like you've already submitted a request to become a partner.",
  EDIT_ATTEMPT_EXCEEDED:
    "You have exceeded the maximum number of edit attempts for this post.",
  EDIT_TIME_EXCEEDED: "You have exceeded the time limit for editing this post.",
  PET_OWNER_ACCOUNT_DELETED: "Pet owner account deleted.",
});

export const SuccessMessage = Object.freeze({
  SUCCESS: "Success",
  SIGNED_UP: "User has been signed up successfully!",
  LOGGED_IN: "You have been logged in Successfully",
  LOGGED_OUT: "Your account has been logged out successfully",
  ACCOUNT_DELETED: "Your account has been deleted successfully",
  SPECIES_CREATED: "Species has been added successfully!",
  BREED_INSERTED: "Breeds inserted successfully!",
  OTP_SENT: "OTP has been sent successfully",
  OTP_RESENT: "OTP has been resent successfully",
  OTP_VERIFIED: "Your OTP has been verified successfully!",
  RESET_PASSWORD: "Password has been updated successfully!",
  PASSWORD_CHANGED: "Password has been changed successfully!",
  PROFILE_UPDATED: "Profile has been updated successfully!",
  VACCINES_CREATED: "Vaccines has been added successfully!",
  PET_PROFILE_CREATED: "Pet Profile has been created successfully!",
  POST_CREATED: "Post has been created successfully!",
  POST_UPDATED: "Post has been updated successfully!",
  LIKE_UPDATED: "Like has been updated successfully!",
  COMMENT_ADDED: "Comment has been added successfully!",
  CMS_CREATED: "CMS has been added successfully!",
  FAQ_ADDED: "FAQ has been added successfully!",
  CMS_EDITED: "CMS has been updated successfully!",
  FAQ_EDITED: "FAQ has been updated successfully!",
  FAQ_DELETED: "FAQ has been deleted successfully!",
  CMS_DELETED: "CMS has been deleted successfully!",
  USER_BLOCKED_BY_ADMIN: "User has been blocked successfully!",
  USER_UNBLOCKED_BY_ADMIN: "User has been unblocked successfully!",
  USER_UNBLOCKED: "User has been unblocked successfully!",
  USER_BLOCKED: "User has been blocked successfully!",
  PET_SHOP_ADDED: "Pet shop has been added successfully!",
  HOSPITAL_ADDED: "Hospital has been added successfully!",
  SHOP_UPDATED: "Shop has been updated successfully!",
  HOSPITAL_UPDATED: "Hospital has been updated successfully!",
  SHOP_DELETED: "Shop has been deleted successfully!",
  HOSPITAL_DELETED: "Hospital has been deleted successfully!",
  SHOP_ACTIVE: "Shop status is updated to Active.",
  SHOP_INACTIVE: "Shop status is updated to Inactive.",
  HOSPITAL_ACTIVE: "Hospital status is updated to Active.",
  HOSPITAL_INACTIVE: "Hospital status is updated to Inactive.",
  TRANSFER_OWNERSHIP:
    "Ownership transfer request has been raised successfully & it should be accepted in next 24 hours.",
  ACCEPT_OWNERSHIP: "Congratulations! You are now the owner of this pet.",
  REJECT_OWNERSHIP: "You have rejected the ownership of the pet.",
  EMAIL_UPDATED: "Email has been updated successfully.",
  MOBILE_UPDATED: "Mobile number has been updated successfully.",
  PROFILE_PRIVATE: "This profile is private.",
  SENDER_BLOCKED_RECEIVER: "You have blocked the receiver.",
  RECEIVER_BLOCKED_SENDER: "You have been blocked by the receiver.",
  PROFILE_PRIVATE_STATUS: "Your profile is private now.",
  PROFILE_PUBLIC_STATUS: "Your profile is public now.",
  FCM_TOKEN_UPDATED: "Notification Token Updated Successfully.",
  PARTNER_REGISTERED:
    "Your request of becoming as a partner has been registered. Plant Book team will coordinate with you.",
  TRANSFER_OWNERSHIP_CANCELLED:
    "Transfer ownership has been cancelled successfully.",
  FEEDBACK_SENT: "Feedback has been sent successfully",
  FEEDBACK_ADDED: "Your feedback has been submitted successfully",
  PET_PROFILE_DELETED: "Pet profile has been deleted successfully.",
  ADMIN_NOTIFICATION: "Notification has been sent successfully.",
  NOTIFICATION_DELETED: "Notification has been deleted successfully.",
  CHAT_DELETED: "User's chat has been deleted successfully.",
});
